# ─────────────────────────────────────────────────────────────────────────────
# G50 development Makefile
#
#   make s1          restart Anvil + deploy + seed (scenario 1)
#   make anvil       start Anvil in the foreground
#   make kill        stop any running Anvil
# ─────────────────────────────────────────────────────────────────────────────

.ONESHELL:
SHELL := /bin/bash

RPC      := http://localhost:8545
# Anvil account 0 — used as the deployer / Alice
DEPLOYER := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

.PHONY: help anvil kill s0 s1 s2 s3 s4

# ── Default target ────────────────────────────────────────────────────────────
help:
	@echo ""
	@echo "  make s0   fresh deploy — no activity"
	@echo "  make s1   three early buyers"
	@echo "  make s2   buys + first price update"
	@echo "  make s3   mixed buys & sells, two price cycles"
	@echo "  make s4   heavy activity, many price cycles"
	@echo ""
	@echo "  make anvil  start Anvil in the foreground"
	@echo "  make kill   stop Anvil"
	@echo ""

# ── Anvil ─────────────────────────────────────────────────────────────────────
anvil:
	anvil --accounts 10 --balance 10000

kill:
	@pkill -f "^anvil" 2>/dev/null && echo "Anvil stopped." || echo "Anvil was not running."

# ── Scenarios ─────────────────────────────────────────────────────────────────
# Each target:
#   1. kills any running Anvil
#   2. starts a fresh Anvil in the background (silent, 10 accounts, 10 000 ETH)
#   3. waits until Anvil is ready
#   4. runs the matching DevSeed scenario (deploys + seeds)
#   5. reads the deployed address from Foundry's broadcast artifact and writes
#      frontend/src/generated/contracts.ts — picked up by Next.js HMR instantly
#
# $@ expands to the target name (s0 … s4), so --sig "$@()" resolves to e.g. --sig "s2()".

BROADCAST = broadcast/DevSeed.s.sol/31337/$@-latest.json

s0 s1 s2 s3 s4:
	@pkill -f "^anvil" 2>/dev/null; sleep 0.3; true
	anvil --accounts 10 --balance 10000 --silent &
	until cast block-number --rpc-url $(RPC) &>/dev/null; do sleep 0.1; done
	forge script script/DevSeed.s.sol \
		--sig "$@()" \
		--rpc-url $(RPC) \
		--broadcast \
		--private-key $(DEPLOYER) \
		--gas-estimate-multiplier 500
	addr=$$(jq -r '[.transactions[] | select(.transactionType=="CREATE")][0].contractAddress' \
		$(BROADCAST)) && \
	printf '// Auto-generated by make %s - do not edit manually.\nexport const G50_ADDRESS = "%s" as const;\nexport const CHAIN_ID = 31337; // Anvil\n' \
		"$@" "$$addr" > frontend/generated/contracts.ts
	echo ""
	echo "  scenario : $@"
	echo "  address  : $$(jq -r '[.transactions[] | select(.transactionType=="CREATE")][0].contractAddress' $(BROADCAST))"
	echo "  rpc      : $(RPC)"
	echo ""
	echo "  Anvil running in background — make kill to stop"
